name: Automated pre_dev to dev

on:
  workflow_dispatch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: create pull request
      run: gh pr create -B dev -H pre_dev --title 'Merge pre_dev into dev' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Pull Request Number
      id: get-pr
      run: |
        PR_NUMBER=$(gh pr list --head pre_dev --json number --jq '.[0].number')
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto-merge Pull Request
      run: gh pr merge ${{ env.PR_NUMBER }} --auto --merge
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
